version: '3'
services:
  derp:
    image: caomingjun/derp:v3.0
    container_name: derp
    restart: always
    environment:
      - DERP_DOMAIN=derp.example.com
      - DERP_ADDR=:80
      - "DERP_STUN=true"
      - TAILSCALE_AUTHKEY=tskey-xxxxxxx
      - TAILSCALE_ARGS=--accept-routes
    cap_add:
      - NET_ADMIN
    ports:
      - 3478:3478/udp
      ## Do not expose 80 to the public, use a reverse proxy instead
      # - 80:80
    volumes:
      - ./data:/var/lib/tailscale
      ## If you want to enable healthcheck, uncomment the following line and pass derpmap.json to the container
      # - ./derpmap.json:/derpmap.json:ro

    ## Optional healthcheck
    # healthcheck:
    #   test: ["CMD", "/bin/bash", "/health.sh"]
    #   interval: 5m
    #   timeout: 30s
    #   retries: 3
    #   start_period: 1m