version: '3'
services:
  derp:
    image: caomingjun.azurecr.io/derp:latest
    container_name: derp
    restart: always
    environment:
      - DERP_DOMAIN=derp.example.com
      - DERP_ADDR=:80
      - "DERP_STUN=true"
      - TAILSCALE_AUTHKEY=tskey-xxxxxxx
      - TAILSCALE_ARGS=--accept-routes
    cap_add:
      - NET_ADMIN
    ports:
      - 3478:3478/udp
      ## Do not expose 80 to the public, use a reverse proxy instead
      # - 80:80
    volumes:
      - ./data:/var/lib/tailscale
